[package]
authors = ["Brennan Chesley <holtchesley@example.com>"]
name = "urql"
version = "0.1.0"

[dependencies]
chrono = "0.4.0"
itertools = "0.6.1"
nom = "3.1.0"

[dev-dependencies]
nom-test-helpers = "3.0.0"
quickcheck = "0.4.1"
