[package]
authors = ["Brennan Chesley <holtchesley@example.com>"]
name = "urql"
version = "0.1.0"

[dependencies]
chrono = "0.4.0"
itertools = "0.6.1"
regex = "0.2.2"
nom = "3.2.0"

[dev-dependencies]
quickcheck = "0.4.1"
nom-test-helpers = "3.0.0"
